stages:
  - test
  - deploy

stage: test
language: python
python:
- '3.6'
- '3.7-dev'
install:
- pip install -U virtualenv pip
- python --version
- echo $TRAVIS_BRANCH
script:
- DOCKER=1 make test-unit-all
- make test-lint-errors
- if [ "$TRAVIS_BRANCH" = "master" ]; then make test-lint; fi

jobs:
  include:
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: thomaslima
        password:
          secure: FbL4S5mRqyZeKt1ZHoEyE53kgkaKBdVfztxbEYfTfhNgaQg94BUmd/x5IWBCORIqF7s0ywkkP+kK9LRFrA5Ymu50hbwAAODnIEEax5xcYE825c0cagXQdKsMG/MGVDGOxlcO+1DQN6zZnfcOVX6fGqm9pEBN2s4Ej0YfabrqdeebvVb53pyCXS43veGXQ8jyMr48eHdig3rksnWb5uKBUrfW1g8wxdCntym4vJRxrdA4zZIuG1osfkxd1sX5rUXcnPNc+6czXwSFsVoRgrr5RvUFYGDGGjuCQ4UVeRe3/V2pSN543FaG6HWP0xpJYGw2dcsML8ykIOIX1oRf2bO2dD485KJHdmkHpgafiB7fnDqwiw0uah/PJkdLtd1tWk4/y0txsEQJhK1qZdHRf5wSfGAIK2XvQPuQXL/MZ8BUIojYd0Ay+JwnkvB57bubGotmvwjWmdDbMMrSWI1B+6UgjHjPN7rQU8qMgV10/IyH51fCvd+2uMQX6D3I7CXS5o8ELy9OsboSxzPxNOxitmq/oGoMKAlg3nhqvYCNZXoxHip+aamqUtccYKaYZuv5ma+WIhAAJt6h5IJ1J3d5wBz6dILXzUYhw3IoXzrGdEG5TSdjrDdmmgxjKrCybxGkbTTLFS69pKa6XGwB9D0qhxKEdJmaFrGojm0zDFOsQwcHse8=
        on:
          tags: true
          branch: master
