name: Publish package

on:
  push:
    branches: [master]
  release:
    types: [published, released]

jobs:
  deploy:
    name: "Publish to PyPI"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build a binary wheel and a source tarball
      run: |
        python -m build --sdist
    - name: Publish package to PyPI
      if: github.event_name == 'release' && github.event.action == 'released'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}