name: Python package

on: [push, pull_request]

jobs:
  test_code:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 12
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -r test-requirements.txt
    - name: Install package and dependencies
      run: |
        pip install .
    - name: Build package from source
      run: |
        python -m build
    - name: Run tests
      run: |
        py.test --capture=sys --cov=lightlab --cov-config .coveragerc
    - name: Run linting
      run: |
        py.test --pylint --flake8 --pylint-rcfile=pylintrc lightlab
      continue-on-error: true